/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_kebun.gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import pbo_kebun.tools.DBConnection;

/**
 *
 * @author bassamtiano
 */
public class TanamanGUI extends javax.swing.JFrame {

    Connection conn;
    
    /**
     * Creates new form TanamanGUI
     */
    public TanamanGUI() {
        initComponents();
        
        DBConnection openconn = new DBConnection();
        this.conn = openconn.create_connection();
        
        this.loadKebunComboBox();
    }
    
    public void loadKebunComboBox() {
        try {
            try {
                String sql = "select * from kebun";
                Statement statement = this.conn.createStatement();
                ResultSet result = statement.executeQuery(sql);
                while (result.next()) {
                    String namaKebun = result.getString(2);
                    CBKebun.addItem(namaKebun);
                }
            }
            catch(SQLException e) {
                e.printStackTrace();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBKebun = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnAdd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MIExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIKebun = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kebun");

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        MIExit.setText("Exit");
        MIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIExitActionPerformed(evt);
            }
        });
        jMenu1.add(MIExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Module");

        MIKebun.setText("Kebun");
        MIKebun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIKebunActionPerformed(evt);
            }
        });
        jMenu2.add(MIKebun);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CBKebun, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAdd)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBKebun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(BtnAdd)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        
        
        int id_kebun = CBKebun.getSelectedIndex() + 1;
        
        System.out.println(id_kebun);
    }//GEN-LAST:event_BtnAddActionPerformed

    private void MIKebunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIKebunActionPerformed
        try {
            new KebunGUI().setVisible(true);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MIKebunActionPerformed

    private void MIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIExitActionPerformed
        try {
            System.exit(0);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MIExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JComboBox<String> CBKebun;
    private javax.swing.JMenuItem MIExit;
    private javax.swing.JMenuItem MIKebun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
